version: '3'

services:
  front:
    image: node:10
    ports:
      - 8080:8080
    command: bash -c "yarn install ; yarn install -g @vue/cli ; yarn serve"
    working_dir: /app
    volumes:
      - ./:/app
