version: '3'

services:
  front:
    image: node:10
    ports:
      - 8080:8080
    command: bash -c "npm install ; npm install -g @vue/cli-init ; HOST=0.0.0.0 npm start"
    working_dir: /app
    volumes:
      - ./:/app
